andela/mrm-deployment-scripts

images/README.md, images/backend-image/backend-template.json.tmpl, images/backend-image/mrm_api.conf, images/backend-image/provisioner.sh, images/backend-image/startup-script.sh, images/shared/filebeat-config.yml, images/shared/metricbeat-config.yml
- Creates and Uploads a packer image to the GCR
[Write API Packer Images](<https://www.pivotaltracker.com/story/show/157738332>)
=> #157738332: Write and Deploy API Images

images/vault-image/README.md, images/vault-image/mrm-vault-config-file.hcl, images/vault-image/mrm-vault-policy.hcl, images/vault-image/renew-token, images/vault-image/startup-script.sh, images/vault-image/vault-provisioner.sh, images/vault-image/vault-template.json.tmpl, images/vault-image/vault.service
- Creates and Uploads a packer image for the vault server to the GCR
[Create and Deploy Vault Server](<https://www.pivotaltracker.com/story/show/157738369>)
=> #157738369: write and deploy vault server

images/circleCI-image/Dockerfile, images/circleCI-image/README.md, images/monitoring/ELK/elk-provisioner.json.tmpl, images/monitoring/ELK/server/elasticsearch-output.conf, images/monitoring/ELK/server/kibana-importer.py, images/monitoring/ELK/server/logstash-beats.conf, images/monitoring/ELK/server/nginx-config, images/monitoring/ELK/server/nginx-filter.conf, images/monitoring/ELK/server/postgres-filter.conf, images/monitoring/ELK/server/postgresql-filter-extra.conf, images/monitoring/ELK/server/provisioner.sh, images/monitoring/ELK/server/syslog-filter.conf, images/monitoring/README.md, images/monitoring/script.sh, terraform/firewall-config.tf, terraform/global-instance-configs.tf, terraform/ip-addresses.tf, terraform/routes.tf, terraform/variables.tf
[158127978](https://www.pivotaltracker.com/story/show/158127978)
=> #158127978: setup elk server

images/database-image/README.md, images/database-image/barman/barman-template.json.tmpl, images/database-image/barman/barman.conf, images/database-image/barman/cron-job, images/database-image/barman/provisioner.sh, images/database-image/postgres/filebeat-config.yml, images/database-image/postgres/postgresql-template.json.tmpl, images/database-image/postgres/provisioner.sh
[157899411](https://www.pivotaltracker.com/story/show/157899411)
=> #157899411 write and deploy database server and barman server

images/README.md, images/nat-image/nat-config.sh, images/nat-image/nat-template.json.tmpl
[157940617](<https://www.pivotaltracker.com/story/show/157940617>)
=> #157940617: write and deploy images for the nat gateway server

images/backend-image/backend-template.json.tmpl, images/backend-image/startup-script.sh, images/frontend-image/frontend-template.json.tmpl, images/frontend-image/nginx-config, images/frontend-image/startup-script.sh, images/shared/slack.sh
- Modify startup scripts
- Modify template files
- Include slack notifier
[](<https://www.pivotaltracker.com/story/show/158152428>)
=> #158152428: Integrate Alerting

terraform/backend-instance-group.tf, terraform/frontend-instance-group.tf
- Modified terraform config to make instance groups across regions (rather than single region)
- Created extra health checks
- Increases availability
- Part of a series of PRs on both the front end, backend projects
[158211220](<https://www.pivotaltracker.com/story/show/158211220>)
=> #158211220: upgrade infrastructure from zonal to regional

images/vault-image/vault-provisioner.sh, terraform/metadata-config.tf
[158257675](<https://www.pivotaltracker.com/story/show/158257675>)
=> #158257675: modify configuration files

images/backend-image/provisioner.sh, images/frontend-image/frontend-provisioner.sh, images/frontend-image/nginx-config, images/frontend-image/startup-script.sh
[158421868](<https://www.pivotaltracker.com/story/show/158421868>)
=> #158421868: Update config

images/backend-image/backend-template.json.tmpl, images/backend-image/startup-script.sh
[158656617](<https://www.pivotaltracker.com/story/show/158656617>)
=> #158656617 provision credentials file

terraform/database.tf, terraform/variables.tf.templ
[159428998](https://www.pivotaltracker.com/n/projects/2154921/stories/159428998)
=> chore(database): setup database with terraform

images/backend-image/startup-script.sh.templ, images/frontend-image/startup-script.sh.templ
[160915347](https://www.pivotaltracker.com/story/show/160915347)
=> #160915347 Modify image variables

terraform/instance-group-template.tf
[160847001](https://www.pivotaltracker.com/story/show/160847001)
=> #160847001 modify instance templates

terraform/global-instance-configs.tf, terraform/instance-group-template.tf, terraform/variables.tf.templ
[161439794](https://www.pivotaltracker.com/story/show/161439794)
=> #161439794 fix terraform environment variable

images/backend-image/backend-template.json.templ, images/backend-image/roles/dependecies/tasks/main.yml
[#161885123](https://www.pivotaltracker.com/story/show/161885123)
=> #161885123 install opencv dependencies

images/backend-image/roles/dependecies/tasks/main.yml, images/backend-image/roles/dependecies/tasks/wkhtmltopdf_install.yml
N/A
N/A
[#62007329](https://www.pivotaltracker.com/story/show/162007329)
=> feat(linux package): Install wkhtmltopdf on backend

images/frontend-image/startup-script.sh.templ, terraform/global-instance-configs.tf, terraform/instance-group-template.tf, terraform/variables.tf.templ
N/A
N/A
[#162348369](https://www.pivotaltracker.com/story/show/162348369)
=> ##162348369 add base url for analytics as environment variable

terraform/backend-instance-group.tf, terraform/frontend-instance-group.tf, terraform/instance-group-template.tf, terraform/routes.tf
- [Frontend](https://converge.andela.com)
- [Backend](https://converge-api.andela.com/mrm) 
[#162631660](https://www.pivotaltracker.com/story/show/162631660)
=> #162631660 create production environment

.gitignore, gke/cluster.tf, gke/network.tf, gke/provider.tf, gke/variables.tf
[163824996](https://www.pivotaltracker.com/story/show/163824996)
=> #163824996 create kubernetes cluster

.gitignore, k8s/backend-deployment.tf, k8s/backend-secret.tf, k8s/backend-service.tf, k8s/namespace.tf, k8s/provider.tf, k8s/variables.tf, main.tf
[#163512827](https://www.pivotaltracker.com/story/show/163512827)
=> feat(backend) Deployments

k8s/Ingress/converge-sandbox-ingress.yml, k8s/Ingress/ingress.sh, k8s/Ingress/nginx-service.yml
* This PR set up an ingress controller that runs in a cluster and configures an HTTP load balancer.
* N/A
N/A
* story type - Chore
* story title - Implement nginx ingress controller
* story id - #163942134
=> #163942134 Implement nginx ingress controller

images/backend-image/startup-script.sh.templ, terraform/instance-group-template.tf, terraform/providers.tf, terraform/variables.tf.templ
[#163938099](https://www.pivotaltracker.com/story/show/163938099)
=> #163938099 Add push notifications environment variable

images/backend/Dockerfile
[#164144343](https://www.pivotaltracker.com/story/show/164144343)
=> #164144343 create backend base image

.circleci/config.yml, .circleci/deploy_to_kubernetes.sh, .gitignore, images/backend/Dockerfile, images/circleci/Dockerfile, k8s/Ingress/ingress.yml, k8s/dashboard-admin.yaml, k8s/ingress-controller.tf, main.tf.templ, supply_values.sh, variables.sh
[#164163187](https://www.pivotaltracker.com/story/show/164163187)
=> #164163187 create deployment pipelines

.circleci/config.yml
[#164448351](https://www.pivotaltracker.com/story/show/164448351)
=> #164448351 fix grep matches on circleci

k8s/microservice-deployment.tf
- change entry point to run with supervisor
[#164462548](https://www.pivotaltracker.com/story/show/164462548)
=> #164462548 run push microservice with supervisor

k8s/Ingress/ingress.yml, k8s/backend-deployment.tf
[#164519743](https://www.pivotaltracker.com/story/show/164519743)
=> #164519743 run backend with supervisor

k8s/backend-autoscaler.tf, k8s/backend-deployment.tf
N/A
N/A
[#165145749](https://www.pivotaltracker.com/story/show/165145749)
N/A
=> feat(auto-scaler): setup auto-scaler for backend

k8s/backend-deployment.tf
[#165437799](https://www.pivotaltracker.com/story/show/165437799)
=> #165437799 backend entry command

k8s/backend-autoscaler.tf, k8s/backend-deployment.tf
=> Add auto-scaler and modify entry point for backend
